service: school-bus

package:
  individually: true

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: true
    external: ['pg-native']
    watch:
      pattern: ['src/**/*.ts']
      ignore: ['.serverless/**/*', '.build']

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  lambdaHashingVersion: 20201221
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
      - 'image/jpeg'
      - 'image/png'
      - 'text/csv'
      - 'application/vnd.ms-excel'

useDotenv: true

functions:
  main:
    architecture: arm64
    handler: src/caller/index.handler
    events:
      - http:
          method: GET
          path: /test
          cors: true
      - http:
          method: GET
          path: /sendSMS
          cors: true
      - http:
          method: GET
          path: /getHornAlarm
          cors: true
      - http:
          method: GET
          path: /setHornAlarm
          cors: true
      - http:
          method: GET
          path: /getMovementAlarm1
          cors: true
      - http:
          method: GET
          path: /setMovementAlarm1
          cors: true
      - http:
          method: GET
          path: /getMovementAlarm2
          cors: true
      - http:
          method: GET
          path: /setMovementAlarm2
          cors: true
      - http:
          method: GET
          path: /getMovementAlarm3
          cors: true
      - http:
          method: GET
          path: /setMovementAlarm3
          cors: true
      - http:
          method: GET
          path: /setCoAlarm
          cors: true
      - http:
          method: GET
          path: /getIGStatus
          cors: true
      - http:
          method: GET
          path: /setIGStatus
          cors: true
      - http:
          method: GET
          path: /getlastCO
          cors: true
      - http:
          method: GET
          path: /getCO
          cors: true
      - http:
          method: GET
          path: /setCO
          cors: true
      - http:
          method: GET
          path: /setSensorValue
          cors: true
      - http:
          method: GET
          path: /getCoAlarm
          cors: true



