name: SchoolBus - Development

on:
  workflow_dispatch:
  push:
    paths:
      - 'api/**'
      - '.github/workflows/dev-CICD.yaml'
    branches:
      - main
jobs:
  deploy:
    name: deploy
    defaults:
      run:
        working-directory: ./api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIARGCOLRN33GDMJW4Y
          aws-secret-access-key: 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
          aws-region: ap-southeast-1
      - name: Deploy
        run: npm run deploy